### ISSUE TITLE
A way to retrieve the total ON/OFF time of an outlet?

### ISSUE THREAD

**Issue by giuliomagnifico** [lstrojny/homebridge-prometheus-exporter#34]
Hi and thanks a lot for this plugin. It's fabulous, I hope it will be keep alive and improved, I just built some of my stat panels (see screenshot), but I was wondering: is there a way to build a panel with the total time of an outlet when is ON?

Probably it would be just a workaround like divide the time by the number of entries etc... but I'm struggling to figure out the correct way, because the exporter use only the 1-0 status but not the timestamp, maybe is possible to implement it? Or any other way to retrieve the same result?

Thanks!

![casa](https://user-images.githubusercontent.com/1975176/203527600-726ac0f7-b1c7-4042-b69d-14e0aa72784e.png)

**Comment by lstrojny** [comment]
This should be possible with `sum_over_time (homebridge_outlet_on[$__range])`. This calculates the "on"-time relative to the currently selected range. So if you have selected 24 hours it would tell you how long it was on in that timeframe. 

![image](https://user-images.githubusercontent.com/79707/203544546-f5ab2709-4c43-434a-95c1-4454ab952ffc.png)

Here is the JSON for the graph

<details>
```
{
  "id": 19,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 8,
    "h": 8
  },
  "type": "gauge",
  "title": "Panel Title",
  "targets": [
    {
      "refId": "A",
      "datasource": {
        "type": "prometheus",
        "uid": "3ad6c16d-4ef5-409b-a6dd-10ae8f486d7d"
      },
      "editorMode": "code",
      "expr": "sum_over_time (homebridge_outlet_on[$__range])",
      "legendFormat": "{{name}}",
      "range": true
    }
  ],
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "showThresholdLabels": false,
    "showThresholdMarkers": false
  },
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "percentage",
        "steps": [
          {
            "color": "blue",
            "value": null
          },
          {
            "value": 50,
            "color": "#EAB839"
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "unit": "m"
    },
    "overrides": []
  },
  "datasource": {
    "uid": "3ad6c16d-4ef5-409b-a6dd-10ae8f486d7d",
    "type": "prometheus"
  },
  "pluginVersion": "9.2.5"
}
```
</details>

**Comment by giuliomagnifico** [comment]
Thanks for the quick reply but... uh, I don't have the `homebridge_outlet_on` metric. Only the `homebridge_switch_outlet_in_use` that has only 0 or 1 has value and I can't use the sum over time function.
 
![Screenshot 2022-11-23 at 13 40 40](https://user-images.githubusercontent.com/1975176/203549770-70581431-e1ed-450b-aae3-0b17fc18dbaa.png)

I'm using the last release: homebridge-prometheus-exporter v0.0.14 and my outlets are from Meross.

Edit: here are all the metrics from your the exporter:

```
homebridge_battery_charging_state
homebridge_battery_level_percentage
homebridge_battery_status_low_battery
homebridge_fanv2_active
homebridge_fanv2_rotation_direction
homebridge_fanv2_rotation_speed_percentage
homebridge_fanv2_swing_mode
homebridge_humidity_sensor_current_relative_humidity_percentage
homebridge_input_source_current_visibility_state
homebridge_input_source_is_configured
homebridge_input_source_target_visibility_state
homebridge_input_source_type
homebridge_lightbulb_brightness_percentage
homebridge_lightbulb_on
homebridge_switch_current_consumption_w
homebridge_switch_on
homebridge_switch_outlet_in_use
homebridge_switch_voltage_v
homebridge_television_active
homebridge_television_active_identifier
homebridge_television_sleep_discovery_mode
homebridge_television_speaker_active
homebridge_television_speaker_mute
homebridge_television_speaker_volume_control_type
homebridge_television_speaker_volume_percentage
homebridge_temperature_sensor_current_temperature_celsius
homebridge_thermostat_current_heating_cooling_state
homebridge_thermostat_current_relative_humidity_percentage
homebridge_thermostat_current_temperature_celsius
homebridge_thermostat_target_heating_cooling_state
homebridge_thermostat_target_temperature_celsius
homebridge_thermostat_temperature_display_units
```

**Comment by lstrojny** [comment]
Well, same there, try `sum_over_time (homebridge_outlet_in_use[$__range])`.

**Comment by giuliomagnifico** [comment]
Okay thanks, this worked: `sum_over_time(homebridge_switch_outlet_in_use[$__range])`. I don't have only the "`outlet`" metric, it fails to retrieve the data. My metric is `switch_outlet`. Don't know why...

Anyway unfortunately for me it doesn't work in a very reliable way because almost all my outlets look like ON/1, because when the watt consumption is above 0, they appears like ON, also if they're in standby. For some appliances, like the microwave or TV, they figure alway ON because during the standby the power consumption is 3-4W. So I have to insert also a query that exclude the outlets with less than 3W of consumption.

If you have any suggestion I would be thankful :)

**Comment by lstrojny** [comment]
You could maybe do something like `some_wattage > bool 3` and then count those over time to get the usage in time.

Closing this issue now as it’s more of a prometheus query question for which there are [better resources](https://prometheus.io/community/).
