### ISSUE TITLE
prometheus exporter not responding on metrics server port

### ISSUE THREAD

**Issue by cosgroveb** [lstrojny/homebridge-prometheus-exporter#540]
**Describe Your Problem:**
After installing and configuring the plugin it does not appear to be listening on the metrics port. Upon further inspection the logs give the following:

**Logs:**

```
2024-01-31T00:42:21.546Z hapNodeJSClient HAP Discover failed Socket -> http://192.168.87.94:56430 invalid PIN or homebridge is not running in insecure mode with -I response.status - 470, response.data - { status: -70411 }, response.statusText - Connection Authorization Required
```

**Plugin Config:**

```json
    "bridge": {
        "name": "Homebridge E936",
        "username": "0E:5A:3B:56:E9:36",
        "port": 51942,
        "pin": "********",
        "advertiser": "avahi",
        "bind": [
            "eth0",
            "wlan0"
        ]
    },
    "accessories": [
],
    "platforms": [
{
    "pin": "********",
    "debug": true,
    "prefix": "homebridge",
    "port": 36123,
    "interface": "::",
    "refresh_interval": 60,
    "request_timeout": 10,
    "discovery_timeout": 20,
    "platform": "PrometheusExporter",
}
]
```

I've redacted the PIN here but the PIN in the plugin config (platforms section) matches the bridge PIN.

Additionally I've got insecure mode enabled in the UI.

**Screenshots:**
<img width="551" alt="image" src="https://github.com/lstrojny/homebridge-prometheus-exporter/assets/162995/14cf811b-7f1d-428b-963e-6a86523ac464">

**Environment:**

* **Plugin Version**: v1.0.5
* **Homebridge Version**: v4.55.1
* **Node.js Version**: v18.16.0
* **NPM Version**: 9.5.1
* **Operating System**: Running `hb-service` under Raspbian GNU/Linux 11 (bullseye)

**Comment by lstrojny** [comment]
Forgive me if it’s a dumb question: did you restart after enabling the insecure mode? The error code and error message look suspiciously like it is still enabled

**Comment by cosgroveb** [comment]
Valid question! The homebridge has been restarted a bunch of times... even the Pi itself. I've had insecure mode for a long time for accessory control for other reasons.

**Comment by lstrojny** [comment]
OK, great we got that out of the way. I am a bit confused why it tries to connect to port 56430 but your homebridge config binds to 51942. Any ideas why that is the case?

**Comment by cosgroveb** [comment]
Sorry just wanted to be 1000% certain I'm in insecure mode so going to leave this here:

`bcosgrove@homebridge:/proc/14382 $ sudo xargs -0 -L1 -a /proc/14382/environ|grep -i insecure
UIX_INSECURE_MODE=1`

**Comment by cosgroveb** [comment]
> OK, great we got that out of the way. I am a bit confused why it tries to connect to port 56430 but your homebridge config binds to 51942. Any ideas why that is the case?

Great question. Looking into that in a minute. Thanks!

**Comment by cosgroveb** [comment]
That log line I pasted is apparently an example of it connecting to ... every accessory in my homebridge? 

`2024-02-01T01:43:21.975Z hapNodeJSClient HAP Discover failed PowerView Hub 2.0 -> http://192.168.87.131:7766 invalid PIN or homebridge is not running in insecure mode with -I response.status - 470, response.data - , response.statusText - Authorization Required`

Did I mis-interpret these logs in thinking the hapNodeJSClient is `homebridge-prometheus-exporter`? I was pretty sure it's a dependency of the exporter...

**Comment by cosgroveb** [comment]
Maybe my logs are showing this: https://github.com/NorthernMan54/Hap-Node-Client/issues/56

Not sure if this is the reason the exporter doesn't appear to be exposing metrics or just a red-herring.

**Comment by cosgroveb** [comment]
OK, this is embarassing. Going with red-herring on that log line. The exporter is working. Disabling debug logging now, backing away, and closing the laptop. Maybe I didn't restart homebridge _enough_ times? 

In any case, sorry for the goose chase. Thanks for the response. Really look forward to getting all this stuff into prometheus.

**Comment by lstrojny** [comment]
No worries, great you got it resolved
