### ISSUE TITLE
PrometheusExporter v1.0.0 works but I get an error in the log

### ISSUE THREAD

**Issue by giuliomagnifico** [lstrojny/homebridge-prometheus-exporter#61]
Just updated and I see this error in my Homebridge log, everything work by the way:

`[PrometheusExporter] ::ffff:192.168.1.6:33520 - "GET /metrics HTTP/1.1" 503 "http://192.168.1.5:36123" "Prometheus/2.36.0-rc0" ""`

(what is _::ffff:192.168.1.6:33520_? Seems to be a mixed address between ipv4 and ipv6)

**Comment by lstrojny** [comment]
The IP address visible in the log is an IPv4 address converted to IPv6. Weither or not that is expected depends on your local network setup but it's not necessarily an issue.
Can you you set the config value "debug" to `true` and check the logs resp. post your log file (please be careful to censor sensitive info)?

**Comment by giuliomagnifico** [comment]
I don't have IPv6 active on my network, maybe this is the cause? Anyway I don't have other log also in debug mode:

`[12/12/2022, 09:36:27] [PrometheusExporter] ::ffff:192.168.1.6:48794 - "GET /metrics HTTP/1.1" 503 "http://192.168.1.5:36123" "Prometheus/2.36.0-rc0" ""`

**Comment by lstrojny** [comment]
Maybe not on a local network level but on a single node instead. Is prometheus running on the same node as homebridge?

**Comment by giuliomagnifico** [comment]
Yes it’s on the same node, but the IP in the log is the Homebridge log. The Prometheus database is on another IP/hardware.

Anyway no problem, if it’s only a log, everything is working, just to report.

**Comment by lstrojny** [comment]
So my guess is the following: while you have IPv6 deactivated in your home network, it seems to be activated on the node itself and that’s why Prometheus shows up as a converted IPv4 address. In case you are wondering, the 503 is issued from the endpoint until the service discovery request comes in, so that’s normal startup behavior. Closing this as there seems to be no issue.
