### ISSUE TITLE
all are not exported

### ISSUE THREAD

**Issue by fate8383** [lstrojny/homebridge-prometheus-exporter#79]
I am not sure if this is a bug or I am blind. I have set it up all, well almost all, exported but I cannot see any of my lights, which are eWeLink zigbee mini in walls, all other eWeLink zigbee are exported like temperature and sensors but not these wall swithces. Are all devices supported? Or some are not going to be exported?

Latest version of all listed being used.

**Comment by fate8383** [comment]
never mind, I discovered that I am blind :)

**Comment by lstrojny** [comment]
Glad you found what you were looking for, closing
