### ISSUE TITLE
non-compliant export format, duplicate TYPE lines

### ISSUE THREAD

**Issue by GrimmiMeloni** [lstrojny/homebridge-prometheus-exporter#96]
**Describe The Bug:**
The exporters format is non-compliant to the text based format specified by Prometheus.
While I have successfully imported from this exporter directly into prometheus itself, I am unable to import into telegraf. 
In case of telegraf, the parsing of the /metrics output leads to errors.
This seems to be a well-known issue with custom exporters. See also https://github.com/prometheus/common/issues/265

It is not clear to me, why prometheus itself though accepts the format. My best guess is that it is less strict when parsing.

**To Reproduce:**
Install the plugin and inspect /metrics afterwards.
The output contains multiple TYPE specifications of the same field, leading to parsing errors.
```
  1 # TYPE homebridge_window_covering_current_position_percentage gauge
  2 homebridge_window_covering_current_position_percentage{bridge="Homebridge 1C64 3C3E",device_id="<REDACTED>",manufacturer="Shelly",model="SHSW-25",name="Rollo Schlafzimmer West",serial_number="<REDACTED>",firmware_revision="1.9.4",hardware_revision="prod-191217"} 100 1673170769987
[... skip lines 3-6...]
  7 # TYPE homebridge_window_covering_current_position_percentage gauge
  8 homebridge_window_covering_current_position_percentage{bridge="Homebridge 1C64 3C3E",device_id="<REDACTED>",manufacturer="Shelly",model="SHSW-25",name="Shelly Greta",serial_number="<REDACTED>",firmware_revision    ="1.9.4",hardware_revision="prod-191217"} 100 1673170769987
```

When telegraf sees this, it fails due to the uncompliant format, with the line 7 effectively repeating the type statement from line 1.

```2023-01-08T09:31:40Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://ds218:36123/metrics: reading text format failed: text format parsing error in line 7: second TYPE line for metric name "homebridge_window_covering_current_position_percentage", or TYPE reported after samples```

**Expected behavior:**
Exporter should adhere to the TEXT format specification, in particular in relation to HELP and TYPE fields. More info here:
https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information
As far as I understand, the fix would be to group all metrics for the same TYPE  under a **single** #TYPE line.

```
  1 # TYPE homebridge_window_covering_current_position_percentage gauge
  2 homebridge_window_covering_current_position_percentage{bridge="Homebridge 1C64 3C3E",device_id="<REDACTED>",manufacturer="Shelly",model="SHSW-25",name="Rollo Schlafzimmer West",serial_number="<REDACTED>",firmware_revision="1.9.4",hardware_revision="prod-191217"} 100 1673170769987
  8 homebridge_window_covering_current_position_percentage{bridge="Homebridge 1C64 3C3E",device_id="<REDACTED>",manufacturer="Shelly",model="SHSW-25",name="Shelly Greta",serial_number="<REDACTED>",firmware_revision="1.9.4",hardware_revision="prod-191217"} 100 1673170769987
[... other groups for different types l...]
```

So effectively, from my example output, line 8 directly follows line 2, and the second TYPE declaration from line 7 disappears.

**Logs:**
omitting, as I deem them non-relevant. Can provide though if necessary.

**Plugin Config:**

```json
        {
            "pin": "<REDACTED>",
            "debug": true,
            "prefix": "homebridge",
            "port": 36123,
            "interface": "::",
            "refresh_interval": 60,
            "request_timeout": 10,
            "discovery_timeout": 20,
            "platform": "PrometheusExporter"
        }
```

**Environment:**

* **Plugin Version**: 1.0.3
* **Homebridge Version**: 1.6.0
* **Node.js Version**: v16.16.0
* **NPM Version**: unknown (using oznu's dockerized HB)
* **Operating System**: Docker

**Comment by lstrojny** [comment]
Thanks for the report, this is indeed a bug. Working on a fix

**Comment by lstrojny** [comment]
Fix is included in the 1.0.4 release, please try again and thanks again for the report.

**Comment by GrimmiMeloni** [comment]
Thanks for the super quick turnaround on this one!
i just gave it a spin. It is still bailing out, however this time due to an unexpected end of stream.
Fix should be easy - the last line simply must be terminated by a line feed, which currently is missing.

@lstrojny do you want to reopen this one, or shall I file a new issue?

**Comment by lstrojny** [comment]
@GrimmiMeloni did another release, see [1.0.5](https://github.com/lstrojny/homebridge-prometheus-exporter/releases/tag/v1.0.5)

**Comment by GrimmiMeloni** [comment]
That did the trick. Thanks once again for the adhoc fix. 👍🏻
